Algoritmo "maior_menor"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Leão
// Data atual  : 23/3/2022

Var
// Seção de Declarações das variáveis
valor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite um número: ")
leia(valor)
se valor >= 10 entao
   escreval("O número", valor, " é maior que 10")
senao
   escreval("O número", valor, " é menor que 10")
Fimse

Fimalgoritmo
