Algoritmo "antecessor e sucessor"
// Descrição   : Programa que pede um número e mostra o seu anttecessor
// Autor(a)    : Gabriel Leão
// Data atual  : 17/3/2022

Var
// Seção de Declarações das variáveis 
numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite um número:")
leia(numero)
escreval("O número digitado foi", numero)
Escreval("O antecessor é", numero - 1)
escreval("O sucessor é", numero + 1)

Fimalgoritmo
