Algoritmo "área retãngulo"
// Descrição   : Um programa que calcula a área de um retângulo
// Autor(a)    : Gabriel Leão
// Data atual  : 17/3/2022

Var
// Seção de Declarações das variáveis 
base, Altura, area: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite a base em cm²: ")
leia(base)
escreva("Digite a altura em cm²: ")
leia(altura)
area <- base * altura
Escreval("A área do retângulo é de", area, "cm²")

Fimalgoritmo
