Algoritmo "parImpar"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Leão
// Data atual  : 23/3/2022

Var
// Seção de Declarações das variáveis
valor: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite um número: ")
leia(valor)
se valor % 2 = 0 entao
   escreval("O número", valor, " é par")
senao
   escreval("O número", valor, " é impar")
Fimse
Fimalgoritmo
