Algoritmo "Dividir"
// Programa para dividir números
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/3/2022

Var
// Seção de Declarações das variáveis 
dividendo, divisor, quociente: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite o dividendo:")
leia(dividendo)
Escreva("Digite o divisor:")
leia(divisor)
quociente <- dividendo / divisor
Escreval(dividendo, " :", divisor, " =", quociente)

Fimalgoritmo