Algoritmo "somar"
// Descrição   : um programa que soma dois números
// Autor(a)    : Gabriel Leão
// Data atual  : 16/3/2022

Var
// Seção de Declarações das variáveis
numero, numero1, somar: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número: ")
leia(numero)
escreva("Digite um número: ")
leia(numero1)
somar <- numero + numero1
escreva(numero," +",numero1, " =", somar)

Fimalgoritmo