Algoritmo "subtrair"
// Descrição   : Um aplicativo para subtrair dois números
// Autor(a)    : Gabriel Leão
// Data atual  : 16/3/2022
Var
// Seção de Declarações das variáveis
minuendo, subtraendo, resto: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite o minuendo:")
leia(minuendo)
Escreva("Digite o subtraendo:")
leia(subtraendo)
resto <- minuendo - subtraendo
Escreval(minuendo, " -", subtraendo, " =", resto)

Fimalgoritmo